name: Build and Push Docker Image

on:
  push:
    branches:
      - master
      - production

jobs:
  build:
    permissions:
      contents: read
      id-token: write

    runs-on: ubuntu-22.04

    steps:
    - name: Checkout
      uses: 'actions/checkout@v5'
      with:
        token: ${{ secrets.DOT_TOKEN_ACTIONS }}

    - name: Setup Docker Buildx Image
      uses: docker/setup-buildx-action@v3

    - id: auth
      name: Authenticate to Google Cloud
      uses: 'google-github-actions/auth@v2'
      with:
        token_format: access_token
        workload_identity_provider: 'projects/773911028616/locations/global/workloadIdentityPools/github-actions/providers/github'
        service_account: 'argocd-robot@invisible-tools.iam.gserviceaccount.com'
        access_token_lifetime: 300s

    - name: Login to artifact registry
      uses: docker/login-action@v3
      with:
        registry: us-west1-docker.pkg.dev
        username: oauth2accesstoken
        password: ${{ steps.auth.outputs.access_token }}

    - name: Set outputs
      id: vars
      run: |
        case "$GITHUB_REF_NAME" in
          production) CLUSTER_NAME=prod-cluster ;;
          master) CLUSTER_NAME=stage-cluster ;;
        esac
        echo "cluster_name=$CLUSTER_NAME" >> "$GITHUB_OUTPUT"
        echo "sha_short=$(git rev-parse --short HEAD)" >> "$GITHUB_OUTPUT"

    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        push: true
        tags: us-west1-docker.pkg.dev/invisible-tools/languagetools/languagetools:${{ steps.vars.outputs.sha_short }}

    - name: Deploy image tag (ArgoCD)
      env:
        GH_TOKEN: ${{ secrets.DOT_TOKEN_ACTIONS }}
      run: >
        gh api /repos/invisible-tech/infra/dispatches
        -f event_type=argocd_deploy_image
        -F client_payload[application]=${{ steps.vars.outputs.cluster_name }}/languagetools.yaml
        -F client_payload[tags]='{
          "app.image.tag": "${{ steps.vars.outputs.sha_short }}",
        }'
